### ISSUE TITLE
remove auth token from Dockerfile this is a security risk!!!!!

### ISSUE THREAD

**Issue by pjlammertyn** [RADar-AZDelta/azd-radar-dev-keun#1]
https://github.com/RADar-AZDelta/azd-radar-dev-keun/blob/6b23bde84e6a73e1e7c42466ec9ce1f18695f8b8/Dockerfile#L12

**Comment by pjlammertyn** [comment]
also remove file from git history

**Comment by BostoenToby** [comment]
This one was an accident, it should use the Token ARG instead
