### ISSUE TITLE
Never store your GCP auth token in a file! This is insecure!!!!

### ISSUE THREAD

**Issue by pjlammertyn** [RADar-AZDelta/azd-radar-dev-keun#2]
https://github.com/RADar-AZDelta/azd-radar-dev-keun/blob/6b23bde84e6a73e1e7c42466ec9ce1f18695f8b8/docker-build.sh#L2

**Comment by BostoenToby** [comment]
This just to pass to the Dockerfile to be able to have access to the Artifact Registry (private NPM repo). This file isn't stored in Git or anywhere else, so why is this insecure?

**Comment by pjlammertyn** [comment]
Because by default, your files are group or even world readable.
So storing tokens a file is a anti-pattern. Because nobody checks the read access, and nobody shreds them if they are no longer needed.

![image](https://github.com/RADar-AZDelta/azd-radar-dev-keun/assets/1187178/93ccf18d-3e27-4996-b6a0-4d3a15c12b50)

**Comment by BostoenToby** [comment]
Understandable, in the latest commit it's stored in a variable in the script and directly used in the docker build command. 
Thanks for the feedback!
